spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reccosdb?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: prod_user
    password: prod_password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false  # Menos logs em produção
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    org.springframework: INFO  # Menos detalhes em produção
    com.aledguedes: INFO