server:
  port: 8080

spring:
  flyway:
    enabled: true
  web:
    locale: pt_BR
  profiles:
    active: ${RECCOS_PROFILE:dev}
  jpa:
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

reccos:
  registration:
    url: ${RECCOS_REGISTRATION_URL:https://reccos.com/api/auth/register}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework: INFO
    com.aledguedes: DEBUG